[package]
name = "josefine-core"
version = "0.0.1"
authors = ["jcm <jmcelwain@gmail.com>"]
edition = "2018"

[dependencies]
memmap = "0.7.0"
iron = "0.6.*"
router = "*"
slog = "2.4.1"
slog-async = "2.3.0"
slog-term = "2.4.0"